### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#10]

**Comment by Jeekhen-zz** [comment]
Agent installed

**Comment by Jeekhen-zz** [comment]
Current running CDH installation

**Comment by Jeekhen-zz** [comment]
connection to db tests are all successful

**Comment by Jeekhen-zz** [comment]
forgot to add user raffles and orchard for all nodes

**Comment by Jeekhen-zz** [comment]
completed challenge 3

**Comment by mfernest** [comment]
👍
