### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#12]

**Comment by Jeekhen-zz** [comment]
Installed Kerberos and configured files

**Comment by Jeekhen-zz** [comment]
Kerberos failed in CM integration

**Comment by Jeekhen-zz** [comment]
due to wrong config as well as not propagated to other clinet

**Comment by Jeekhen-zz** [comment]
Forgot to install kdc client on all the nodes

**Comment by Jeekhen-zz** [comment]
Realise i may need to install kerberos server on the Master node. Maybe? Cause error could not find ktutil

**Comment by Jeekhen-zz** [comment]
regreted never run a test user .... =( I am sorry

`Oh the shame...`

**Comment by Jeekhen-zz** [comment]
Error here. kinit: Client 'cloudera-scm@JEEKHEN.COM' not found in Kerberos database while getting initial credentials...... maybe due to not add the correct principal

**Comment by Jeekhen-zz** [comment]
Realised everything was right just that i was too hasty to type the wron Realm in my setup wizard of cloudera

**Comment by Jeekhen-zz** [comment]
Kerberos successfully deployed

**Comment by Jeekhen-zz** [comment]
Terasort In Progress

**Comment by Jeekhen-zz** [comment]
Completed lab 40 min after submission

**Comment by mfernest** [comment]
This is the intended effect of time pressure. You recovered well, however, and finished the job. Impressive. 👍
