### ISSUE TITLE
Installation Labs

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#2]

**Comment by Jeekhen-zz** [comment]
The link to Cloudera Supported OS is broken. I found the relative information in this new URL. http://www.cloudera.com/downloads/cdh/5-8-2.html.

**Comment by Jeekhen-zz** [comment]
Figuring out how to check reserved space on my RHEL 7.2

**Comment by mfernest** [comment]
I've repaired the supported OS link -- thanks.

Check your file system type. `xfs` is an extent-based file system and does not use reserved space for root.

**Comment by Jeekhen-zz** [comment]
Completed Lab

**Comment by mfernest** [comment]
`0_nodeIPs.md` - as standard practice for a Hadoop installation, remember to delete any IPv6 configurations, even in `/etc/hosts`
`1_preinstall.md` - note the inet6 configurations -- bad mojo.
`2_replica_working.md` - good
`3_cm_installed.png` - good

Good work!
