### ISSUE TITLE
Storage Lab

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#3]

**Comment by Jeekhen-zz** [comment]
Could not run Teragen initially. Identified 1 problem and solve it. AWS instance running out of space.

**Comment by Jeekhen-zz** [comment]
Teragen ran to long and relooked into the code. Realized had generated too much data. Stop MR job using mapred job -list and -kill. Restarted job accordingly

**Comment by Jeekhen-zz** [comment]
CM URL:
http://ec2-54-179-163-208.ap-southeast-1.compute.amazonaws.com:7180/

**Comment by mfernest** [comment]
👍
