### ISSUE TITLE
Security Labs

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#5]

**Comment by Jeekhen-zz** [comment]
configured jeekhen/admin as a principal but fail to run kinit

**Comment by Jeekhen-zz** [comment]
also trying to understand the configuration file kadmin5.acl. Trying to figure out how to define a user is using admin instance

**Comment by Jeekhen-zz** [comment]
KDC is now having a valid renewable ticket. the start and expire date is the same.

**Comment by Jeekhen-zz** [comment]
fixed all problem.
1) /admin is giving it admin privileges
2) Re-initialized the KDC to fix renewable ticket problem

**Comment by Jeekhen-zz** [comment]
Commencing TLS

**Comment by Jeekhen-zz** [comment]
stuck in generating a self-sign certificate. SCM server could not start as there is no .keystore file

**Comment by Jeekhen-zz** [comment]
Solved by including in cloudera manager the location of jks location

**Comment by mfernest** [comment]
👍
