### ISSUE TITLE
Install MySQL

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#8]

**Comment by Jeekhen-zz** [comment]
Copying PEM file so that we can do SSH internally

**Comment by Jeekhen-zz** [comment]
Adding /etc/host file for convenient

**Comment by Jeekhen-zz** [comment]
Modified Security Group Policy in AWS

**Comment by Jeekhen-zz** [comment]
Finished installation and started + run initial setup for mysqld

**Comment by Jeekhen-zz** [comment]
Created all users and databases in mysql

**Comment by Jeekhen-zz** [comment]
Completed

**Comment by mfernest** [comment]
👍
