### ISSUE TITLE
Install CM

### ISSUE THREAD

**Issue by Jeekhen-zz** [Jeekhen/SEBC#9]

**Comment by Jeekhen-zz** [comment]
Pre-setup commencing. Turing Selinux, VMSwappines, installing ntp service etc.

**Comment by Jeekhen-zz** [comment]
pre configuration done. Starting yum setup and installation for CM

**Comment by Jeekhen-zz** [comment]
Ran into error. ran '/usr/share/cmf/schema/scm_prepare_database.sh -hec2-54-251-190-59.ap-southeast-1.compute.amazonaws.com mysql scm scm password'. Access Denied.

**Comment by Jeekhen-zz** [comment]
Solved. Entered wrong password.

**Comment by Jeekhen-zz** [comment]
Completed

**Comment by mfernest** [comment]
👍
